[package]
name = "charcoal"
version = "0.1.0"
edition = "2021"
authors = ["LitiaEeloo"]

[dependencies]
url = "2"
anyhow = "1.0"
# futures = { version = "0.3", features = ["executor"] }
log = "0.4"
env_logger = "0.9"
clap = { version = "3.2", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.13"
# tts = "0.22"
google_speech = "0.1"
colored = "2.0"
