[package]
name = "charcoal"
version = "0.1.0"
edition = "2021"
authors = ["LitiaEeloo <litiaeeloo@gmail.com>"]
description = "Charcoal, a command line dictionary"
readme = "Readme.md"

[dependencies]
# error handling
anyhow = "1.0"

# async
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3", features = ["executor"] }

# logging
log = "0.4"
env_logger = "0.9"

# serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"
bincode = "1.3"

# cli
clap = { version = "3.2", features = ["derive"] }
colored = "2.0"

# path management
directories-next = "2.0"

# web
url = "2"
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.13"

# text to speech
google_speech = "0.1"
# tts = "0.22"
# https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=en&q=hibernate
